import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import { Document, Packer, Paragraph, ImageRun } from 'docx'
import JSZip from 'jszip'
import type { Page, ScanDocument } from '../types'
import { storage } from './storage'
import { download } from './image'

const safe = (value: string) => value.replace(/[^a-z0-9-_]+/gi, '-').replace(/^-|-$/g, '') || 'scan'
export async function buildPdf(scanDocument: ScanDocument, pages: Page[], kind: 'pdf' | 'searchable' | 'text-pdf' = 'pdf') {
  const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica)
  for (const pageData of pages) { const page = pdf.addPage([595, 842]); if (kind !== 'text-pdf') { const imageBlob = await storage.blob(pageData); const imageBytes = await imageBlob.arrayBuffer(); const image = imageBlob.type.includes('png') ? await pdf.embedPng(imageBytes) : await pdf.embedJpg(imageBytes); const scale = Math.min(555 / image.width, 802 / image.height); page.drawImage(image, { x: (595 - image.width * scale) / 2, y: (842 - image.height * scale) / 2, width: image.width * scale, height: image.height * scale }) } if (pageData.text) page.drawText(pageData.text.slice(0, 9000), { x: 20, y: kind === 'text-pdf' ? 800 : 20, size: kind === 'text-pdf' ? 11 : 1, color: kind === 'text-pdf' ? rgb(0.1, 0.1, 0.1) : rgb(1, 1, 1), font, maxWidth: 555, lineHeight: 14 }) }
  void scanDocument; const bytes = await pdf.save(); return new Blob([bytes.buffer as ArrayBuffer], { type: 'application/pdf' })
}
export async function exportFile(scanDocument: ScanDocument, pages: Page[], kind: string) { const name = safe(scanDocument.title); if (kind === 'pdf' || kind === 'searchable' || kind === 'text-pdf') { download(await buildPdf(scanDocument, pages, kind), `${name}.pdf`); return } if (kind === 'docx' || kind === 'editable-docx') { const children = []; for (const page of pages) { if (kind === 'editable-docx' && page.text) children.push(new Paragraph(page.text)); else { const blob = await storage.blob(page); children.push(new Paragraph({ children: [new ImageRun({ type: 'jpg', data: new Uint8Array(await blob.arrayBuffer()), transformation: { width: 520, height: Math.min(700, 520 * page.height / page.width) } })] })) } } const data = await Packer.toBlob(new Document({ sections: [{ children }] })); download(data, `${name}.docx`); return } if (kind === 'zip') { const zip = new JSZip(); for (let index = 0; index < pages.length; index++) zip.file(`${name}-${index + 1}.jpg`, await storage.blob(pages[index])); download(await zip.generateAsync({ type: 'blob' }), `${name}.zip`); return } const page = pages[0]; if (!page) return; const blob = await storage.blob(page); const canvas = document.createElement('canvas'); const image = await createImageBitmap(blob); canvas.width = image.width; canvas.height = image.height; canvas.getContext('2d')!.drawImage(image, 0, 0); image.close(); const mime = kind === 'png' ? 'image/png' : kind === 'webp' ? 'image/webp' : 'image/jpeg'; canvas.toBlob(value => value && download(value, `${name}.${kind === 'jpeg' ? 'jpg' : kind}`), mime, .94) }
