import type { Filter } from '../types'
export async function processImage(file: Blob, filter: Filter, rotation: number): Promise<Blob> {
  const bitmap=await createImageBitmap(file); const canvas=document.createElement('canvas'); const turned=rotation===90||rotation===270
  canvas.width=turned?bitmap.height:bitmap.width; canvas.height=turned?bitmap.width:bitmap.height; const c=canvas.getContext('2d')!; c.save(); c.translate(canvas.width/2,canvas.height/2); c.rotate(rotation*Math.PI/180); c.drawImage(bitmap,-bitmap.width/2,-bitmap.height/2); c.restore();
  if(filter!=='original') { const data=c.getImageData(0,0,canvas.width,canvas.height); const p=data.data; for(let i=0;i<p.length;i+=4){ const l=.2126*p[i]+.7152*p[i+1]+.0722*p[i+2]; if(filter==='black-white'){const v=l>155?255:0;p[i]=p[i+1]=p[i+2]=v}else if(filter==='document'){const v=Math.min(255,Math.max(0,(l-120)*1.9+120));p[i]=p[i+1]=p[i+2]=v}else if(filter==='receipt'){const v=Math.min(255,Math.max(0,(l-100)*2.35+100));p[i]=p[i+1]=p[i+2]=v}else {p[i]=Math.min(255,p[i]*1.1);p[i+1]=Math.min(255,p[i+1]*1.12);p[i+2]=Math.min(255,p[i+2]*1.05)}} c.putImageData(data,0,0) }
  bitmap.close(); return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image encoding failed')),'image/jpeg',.94))
}
export async function imageDimensions(file:Blob){const b=await createImageBitmap(file);const r={width:b.width,height:b.height};b.close();return r}
type Point = { x: number; y: number }
function homography(source: Point[], width: number, height: number) { const rows: number[][] = []; const values: number[] = []; const target = [{ x: 0, y: 0 }, { x: width, y: 0 }, { x: width, y: height }, { x: 0, y: height }]; for (let i = 0; i < 4; i++) { const { x, y } = target[i]; const { x: u, y: v } = source[i]; rows.push([x, y, 1, 0, 0, 0, -u * x, -u * y]); values.push(u); rows.push([0, 0, 0, x, y, 1, -v * x, -v * y]); values.push(v) } for (let i = 0; i < 8; i++) { let pivot = i; for (let row = i + 1; row < 8; row++) if (Math.abs(rows[row][i]) > Math.abs(rows[pivot][i])) pivot = row; [rows[i], rows[pivot]] = [rows[pivot], rows[i]]; [values[i], values[pivot]] = [values[pivot], values[i]]; const divisor = rows[i][i] || 1; for (let col = i; col < 8; col++) rows[i][col] /= divisor; values[i] /= divisor; for (let row = 0; row < 8; row++) if (row !== i) { const factor = rows[row][i]; for (let col = i; col < 8; col++) rows[row][col] -= factor * rows[i][col]; values[row] -= factor * values[i] } } return [...values, 1] }
export async function perspectiveCrop(file: Blob, corners: Point[]) { const bitmap = await createImageBitmap(file); const sourceCanvas = document.createElement('canvas'); sourceCanvas.width = bitmap.width; sourceCanvas.height = bitmap.height; const sourceContext = sourceCanvas.getContext('2d', { willReadFrequently: true })!; sourceContext.drawImage(bitmap, 0, 0); const source = sourceContext.getImageData(0, 0, bitmap.width, bitmap.height); const topWidth = Math.hypot(corners[1].x - corners[0].x, corners[1].y - corners[0].y); const bottomWidth = Math.hypot(corners[2].x - corners[3].x, corners[2].y - corners[3].y); const leftHeight = Math.hypot(corners[3].x - corners[0].x, corners[3].y - corners[0].y); const rightHeight = Math.hypot(corners[2].x - corners[1].x, corners[2].y - corners[1].y); const width = Math.max(1, Math.round(Math.max(topWidth, bottomWidth))); const height = Math.max(1, Math.round(Math.max(leftHeight, rightHeight))); const h = homography(corners, width, height); const output = new ImageData(width, height); for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { const denominator = h[6] * x + h[7] * y + 1; const sourceX = Math.max(0, Math.min(bitmap.width - 1, Math.round((h[0] * x + h[1] * y + h[2]) / denominator))); const sourceY = Math.max(0, Math.min(bitmap.height - 1, Math.round((h[3] * x + h[4] * y + h[5]) / denominator))); const from = (sourceY * bitmap.width + sourceX) * 4; const to = (y * width + x) * 4; output.data[to] = source.data[from]; output.data[to + 1] = source.data[from + 1]; output.data[to + 2] = source.data[from + 2]; output.data[to + 3] = 255 } const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d')!.putImageData(output, 0, 0); bitmap.close(); return new Promise<Blob>((resolve, reject) => canvas.toBlob(value => value ? resolve(value) : reject(new Error('Perspective correction failed')), 'image/jpeg', .95)) }
export async function cropImage(file: Blob, inset = .08) { const image = await createImageBitmap(file); const left = Math.round(image.width * inset); const top = Math.round(image.height * inset); const canvas = document.createElement('canvas'); canvas.width = image.width - left * 2; canvas.height = image.height - top * 2; canvas.getContext('2d')!.drawImage(image, left, top, canvas.width, canvas.height, 0, 0, canvas.width, canvas.height); image.close(); return new Promise<Blob>((resolve, reject) => canvas.toBlob(value => value ? resolve(value) : reject(new Error('Crop failed')), 'image/jpeg', .95)) }
export function download(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
